[book]
authors = ["Yasin Gündüz"]
language = "en"
multilingual = false
src = "src"
title = "crate-of-the-week"

[output.html]
number-chapters = false
git-repository-url = "https://github.com/yguenduez/crate-of-the-week"
